### ISSUE TITLE
Add a Carousel with 3 images

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#1]
## Replace This section with A Carousel
<img width="1470" alt="Screenshot 2022-10-15 at 10 12 50 PM" src="https://user-images.githubusercontent.com/72909842/195998131-45231ade-47cd-40d9-9aea-c758dcbc3e02.png">

# Carousel
![138546920-b31c6012-ab54-4419-9588-c9b0dca0ffb9](https://user-images.githubusercontent.com/72909842/195998128-b3455e0d-b903-4b8c-a978-dc39653af22d.png)

**Comment by SrigiriSruthi** [comment]
@Karan2310 can u assign this to me?

**Comment by Karan2310** [comment]
Sure!

**Comment by sp-gits** [comment]
Can you assign this issue to me?

**Comment by SarthakDeshmukh13** [comment]
_I would like to resolve this Issue._

**Comment by brupadhyay** [comment]
@Karan2310 Is it resolved ?, I would like to take this up!

**Comment by Karan2310** [comment]
@SrigiriSruthi Still working on it?

**Comment by SrigiriSruthi** [comment]
> @SrigiriSruthi Still working on it?

yep.

**Comment by SrigiriSruthi** [comment]
almost done. @Karan2310

**Comment by Karan2310** [comment]
@SrigiriSruthi update? else please let me know I would assign someone else please!

**Comment by kritika902** [comment]
plzz assign this to me

**Comment by brupadhyay** [comment]
No offense, @Karan2310 you're a maintainer your priority is to support contributors but what if October Month ends meanwhile we keep commenting on this.......

**Comment by Karan2310** [comment]
> No offense, @Karan2310 you're a maintainer your priority is to support contributors but what if October Month ends meanwhile we keep commenting on this.......

The issue is already assigned to someone and the person is already working on it, so what's the sense of spamming on the same issue and wasting your own time. We have multiple repos and multiple issues, comment there I guarantee you will be assigned if it is not assigned to anyone else :)

**Comment by Karan2310** [comment]
> almost done. @Karan2310

@SrigiriSruthi if possible please do it by tomorrow else this issue will be passed on to the next person commented on this issue

**Comment by srishtig2412** [comment]
Hi please assign this issue to me

**Comment by SrigiriSruthi** [comment]
> > almost done. @Karan2310
> 
> @SrigiriSruthi if possible please do it by tomorrow else this issue will be passed on to the next person commented on this issue

sure.. finishing it today!
