### ISSUE TITLE
Make date dynamic (working as per current date)

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#10]
<img width="1470" alt="Screenshot 2022-10-15 at 10 29 56 PM" src="https://user-images.githubusercontent.com/72909842/195999131-a7332b66-393e-46fb-8302-0c0d9b715afd.png">

**Comment by HarshBhakkad** [comment]
Please assign me this issue.

**Comment by Omkar-2003** [comment]
> Please assign me this issue.

sure

**Comment by Adityageek** [comment]
Hi @Omkar-2003 are you working on this issue

**Comment by Omkar-2003** [comment]
Yes

**Comment by Omkar-2003** [comment]
> Hi @Omkar-2003 are you working on this issue

I am Maintainer For this Project

**Comment by Adityageek** [comment]
Hello @Karan2310 @Omkar-2003 I already done this changes with my other code so we can close this issue as well.
