### ISSUE TITLE
A dummy alert on form submit in footer [ Message Sent Succesfully! (Only Frontend) ]

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#11]
<img width="526" alt="Screenshot 2022-10-15 at 10 41 01 PM" src="https://user-images.githubusercontent.com/72909842/195999248-3882f5e6-3d65-4da8-83c0-e3b24e4a517e.png">

**Comment by Adityageek** [comment]
Hi @Karan2310 Can you please assigned this issue. I will be looking forward to work on it.

**Comment by Karan2310** [comment]
> Hi @Karan2310 Can you please assigned this issue. I will be looking forward to work on it.

You can proceed!

**Comment by Adityageek** [comment]
Hi @Karan2310 I have done the changes can you please merge the changes
