### ISSUE TITLE
Add Background gradient (grey-black) in footer

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#12]
<img width="479" alt="Screenshot 2022-10-15 at 10 53 04 PM" src="https://user-images.githubusercontent.com/72909842/195999701-bd5d5e58-45da-4357-997a-eeff7f36d9a1.png">

**Comment by HarshBhakkad** [comment]
Can you assign me this issue?

**Comment by Karan2310** [comment]
> Can you assign me this issue?

Yes, You can proceed

**Comment by HarshBhakkad** [comment]
Is any shade from the given plate acceptable? Or the same colour gradient schema needs to be applied?

**Comment by Karan2310** [comment]
Similar to the one shown in the above image

**Comment by roopaviany** [comment]
please assign it to me

**Comment by HarshBhakkad** [comment]
I have generated a pull request, please check.

**Comment by Karan2310** [comment]
> I have generated a pull request, please check.

Sure we will have a look once, please wait... 🙂
