### ISSUE TITLE
Make Navbar Mobile Responsive

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#2]
<img width="291" alt="Screenshot 2022-10-15 at 10 21 13 PM" src="https://user-images.githubusercontent.com/72909842/195998435-6fb0666f-4a8f-40df-8ab6-507e3c7daf2e.png">

**Comment by Adityageek** [comment]
Hi @Karan2310 Can you please assign this issue. I will be looking forward to work on it

**Comment by Karan2310** [comment]
Sure!

**Comment by Adityageek** [comment]
Hi @Karan2310 can you please assign me again unintenionally i unassigned myself

**Comment by Karan2310** [comment]
> Hi @Karan2310 can you please assign me again unintenionally i unassigned myself

Np! Done :)

**Comment by Adityageek** [comment]
Pull request is there can you please approve the same.
