### ISSUE TITLE
Redesign About Section

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#3]
<img width="1470" alt="Screenshot 2022-10-15 at 10 29 08 PM" src="https://user-images.githubusercontent.com/72909842/195998841-5f51cd9e-bd1d-4f3a-aaa0-44cbc88ea648.png">

**Comment by SrigiriSruthi** [comment]
@Karan2310 can u assign this to me?

**Comment by Karan2310** [comment]
Sure!

**Comment by sp-gits** [comment]
Can you assign this issue to me?

**Comment by ayusshh19** [comment]
pls assign me this issue

**Comment by MansiBhayade** [comment]
can you assign this issue to me ?

**Comment by technophileADITYA** [comment]
Hey, @Karan2310 I`m inquisitive about this. Please are you capable of assign it to me?
