### ISSUE TITLE
Make navbar stick to top on scroll

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#32]

**Comment by SarthakDeshmukh13** [comment]
_I would like to resolve this Issue._

**Comment by Karan2310** [comment]
![Nahi-meme-template-on-Sanjay-Dutt-1024x576](https://user-images.githubusercontent.com/72909842/196489894-f40c531c-b054-41cc-886e-0991d8047032.jpeg)

**Comment by Karan2310** [comment]
> _I would like to resolve this Issue._

Sure!

**Comment by C-V-Anish** [comment]
I would love to contribute. Please assign me the issue.

**Comment by RashiSingh20** [comment]
I would like to work on this

**Comment by RashiSingh20** [comment]
#33 Kindly check to merge
