### ISSUE TITLE
Updating README.md file with git commands

### ISSUE THREAD

**Issue by pawar-jaydeep** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#36]
As I see in many repos there is a specific section in their README.md with git commands for beginners.
so I also want to add some simple git commands which help beginner to contribute to this repo with CLI .

**Comment by pawar-jaydeep** [comment]
Will you pls assign this issue to me?

**Comment by kritika902** [comment]
plzzz assign this to me

**Comment by Manishgupta200** [comment]
Assign it to me. You can show my readme file as areference

**Comment by Karan2310** [comment]
@pawar-jaydeep we have our new readme so if you can improve it then we can merge it :)

**Comment by pawar-jaydeep** [comment]
@Karan2310 Should I wait to assign this issue to me? or
can I directly start working on it?
