### ISSUE TITLE
Redesign Skills Section

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#4]
<img width="1470" alt="Screenshot 2022-10-15 at 10 29 14 PM" src="https://user-images.githubusercontent.com/72909842/195998870-74543f3a-f8b9-40a8-b526-91d2d2072b23.png">

**Comment by bubblecode76** [comment]
can you pls assign this to me?

**Comment by Karan2310** [comment]
Sure

**Comment by bubblecode76** [comment]
sorry to ask this question but do you want me to redesign with a style of my own or did you want me to incorporate the style that you have posted the picture(because this seems to be done)?i would definitely make a style of my own if you want to but i just wanted to confirm my doubt.

**Comment by Karan2310** [comment]
> sorry to ask this question but do you want me to redesign with a style of my own or did you want me to incorporate the style that you have posted in the picture(because this seems to be done)?I would definitely make a style of my own if you want to but i just wanted to confirm my doubt.

You can develop your own design, as of now it is how it looks in the image.

**Comment by bubblecode76** [comment]
ok thank you so much
