### ISSUE TITLE
Redesign Education Section

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#5]
<img width="1470" alt="Screenshot 2022-10-15 at 10 29 26 PM" src="https://user-images.githubusercontent.com/72909842/195998914-7ca8c554-90a4-40bb-8521-58c6f54f19fa.png">

**Comment by Khushi-dev-1822** [comment]
Hey, can you assign me this task??

**Comment by Khushi-dev-1822** [comment]
Hey, can you assign me this task??

**Comment by SarthakDeshmukh13** [comment]
_I would like to resolve this Issue._

**Comment by Karan2310** [comment]
> Hey, can you assign me this task??

Sure!

**Comment by Khushi-dev-1822** [comment]
Hi. Thank you for merging. Is it not worth hacktoberfest
 label??

**Comment by Karan2310** [comment]
@Khushi-dev-1822 It already has all the required label, kindly check!

**Comment by Khushi-dev-1822** [comment]
ah I see, Thank you :)
