### ISSUE TITLE
Create a project cards in a 3 X 2 Grid

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#6]
<img width="1470" alt="Screenshot 2022-10-15 at 10 29 36 PM" src="https://user-images.githubusercontent.com/72909842/195998989-54999517-f3cf-4c06-8b4f-c1da1e0f1764.png">

**Comment by brupadhyay** [comment]
@Karan2310 Would like to take this up! Please assign me

**Comment by Karan2310** [comment]
Sure!

**Comment by brupadhyay** [comment]
@Karan2310 PR is made please review!
