### ISSUE TITLE
Redesign Footer

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#7]
<img width="1470" alt="Screenshot 2022-10-15 at 10 29 43 PM" src="https://user-images.githubusercontent.com/72909842/195999040-73c0d2eb-72e0-4afa-97d1-673cc2d63ca0.png">

**Comment by Sodium-Sharma** [comment]
@Karan2310 i can redesign whole footer for you, assign me.

**Comment by Omkar-2003** [comment]
> @Karan2310 i can redesign whole footer for you, assign me.

Okay

**Comment by SnehaDeshmukh28** [comment]
Can you assign this issue to me ?

**Comment by Karan2310** [comment]
Sure!

**Comment by SarthakDeshmukh13** [comment]
_I would like to work on resolving this Issue ._

**Comment by ayusshh19** [comment]
pls assign me this issue

**Comment by MansiBhayade** [comment]
can you assign me this issue ?

**Comment by pjyoti121** [comment]
Please assign me this issue
