### ISSUE TITLE
Add Icons to social links

### ISSUE THREAD

**Issue by Karan2310** [Google-Developer-Students-Club-DMCE/Student-Portfolio-Hactoberfest-2022#8]
<img width="225" alt="Screenshot 2022-10-15 at 10 35 48 PM" src="https://user-images.githubusercontent.com/72909842/195999062-2c84f939-1a37-4be5-abc8-fe3beecfb47d.png">

**Comment by Sodium-Sharma** [comment]
@Karan2310  i can work on this, assign me.

**Comment by Karan2310** [comment]
Assigneed!

**Comment by Sodium-Sharma** [comment]
@Karan2310  can u merge my last pull request so that i can push this one.

**Comment by Karan2310** [comment]
> @Karan2310 can u merge my last pull request so that i can push this one.

Done
